name: pybandit-dev
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - cython>=3.0.8
  - numpy
  - scipy
  - pandas
  # For testing and benchmarking
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-timeout
  - pytest-fail-slow
  - asv >=0.6
  - hypothesis
  - array-api-strict
  # For linting
  - ruff>=0.0.292
  - cython-lint