blank_issues_enabled: true
contact_links:
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/pybandit
    about: Please ask and answer usage questions on Stack Overflow
  - name: Blank issue
    url: https://github.com/pybandit/pybandit/issues/new
    about: Please note that other templates should be used in most cases
