name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.3.7
      - run: | 
          ruff check .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'