name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.3.7
      - run: |
          pip install ruff==0.3.7
          ruff check .
          ruff format .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'FIX: style fix by ruff'
